rust:
    directory: ..
    manifestPath: Cargo.toml

web:
    features: ["wasm_js"]
    defaultFeatures: false
    target: web
    manifestPatchFile: wasm-manifest-patch.toml
    entrypoint: src/web/index.js
    tsBindings: src/web/generated
