[build-system]
requires = ["setuptools>=83", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "payjoin"
description = "The Python language bindings for the Payjoin Dev Kit"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
version = "0.2.0"
dependencies = ["httpx>=0.28.1,<1.0"]

[tool.setuptools]
packages = ["payjoin"]
package-dir = { "payjoin" = "src/payjoin" }
include-package-data = true

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = ["yapf==0.43.0"]
