name: General Bug Report
description: Submit a new bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ### This issue tracker is only for technical issues related to the following crates:
        - [`payjoin-cli`](https://github.com/payjoin/rust-payjoin/tree/master/payjoin-cli)
        - [`payjoin-directory`](https://github.com/payjoin/rust-payjoin/tree/master/payjoin-directory)
        - [`payjoin-test-utils`](https://github.com/payjoin/rust-payjoin/tree/master/payjoin-test-utils)
        - [`payjoin-ffi`](https://github.com/payjoin/rust-payjoin/tree/master/payjoin-ffi)

        ### For bugs relating to the [payjoin](https://github.com/payjoin/rust-payjoin/tree/master/payjoin) crate, [see here](./bug-payjoin-crate.yml).

        ----
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    attributes:
      label: Which crate is this issue for?
      multiple: false
      options:
        - payjoin-cli
        - payjoin-directory
        - payjoin-test-utils
        - payjoin-ffi
        - ohttp-relay
  - type: dropdown
    attributes:
      label: How did you obtain this crate?
      multiple: false
      options:
        - Compiled from source
        - Pre-built binaries
        - Package manager
        - Docker Image
        - Other
    validations:
      required: true
  - type: textarea
    id: features
    attributes:
      label: Features
      description: |
        If you selected "Compiled from source" what features did you use?
    validations:
      required: false
  - type: input
    id: pdk-version
    attributes:
      label: What version of the selected crate are you using?
      description:
        Run `payjoin-cli --version` or `payjoin-directory --version` for the binaries.
        For the library crates (`payjoin-test-utils`, and `payjoin-ffi`),
        check your respective package manager file to see which version you have installed.
      placeholder: e.g. payjoin-0.23.0 or master@ceef77b
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: Tell us what went wrong
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Tell us what you expected to happen
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: |
        Tell us how to reproduce your bug. Please attach related screenshots if necessary.
        * Run-time or compile-time configuration options
        * Actions taken
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output.

        Please be aware that the log might contain personally identifying information.
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating system and version
      placeholder: e.g. "MacOS Ventura 13.2" or "Ubuntu 22.04 LTS"
    validations:
      required: true
