name: Good First Issue
description: (Regular devs only) Suggest a new good first issue
labels: [good first issue]
body:
  - type: dropdown
    attributes:
      label: Which crate is this issue for?
      multiple: true
      options:
        - payjoin
        - payjoin-cli
        - payjoin-directory
        - payjoin-test-utils
        - payjoin-ffi
        - ohttp-relay
  - type: markdown
    attributes:
      value: |
        Please add the label "good first issue" manually before or after opening

        A good first issue is an uncontroversial issue, that has a relatively unique and obvious solution

        Motivate the issue and explain the solution briefly
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Motivate the issue
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible solution
      description: Describe a possible solution
    validations:
      required: false
  - type: textarea
    id: useful-skills
    attributes:
      label: Useful Skills
      description: For example, “Familiarity with BIP 77”.
  - type: textarea
    attributes:
      label: Guidance for new contributors
      description: Please leave this to automatically add the footer for new contributors
      value: |
        Want to work on this issue?

        For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/payjoin/rust-payjoin/blob/master/.github/CONTRIBUTING.md) before opening your pull request.
