[package]
name = "payjoin-fuzz"
version = "0.0.1"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[features]
default = []

[dependencies]
arbitrary = { version = "1.0.1" }
libfuzzer-sys = { version = "0.4.10" }
payjoin = { path = "../payjoin", default-features = false, features = [
  "arbitrary",
  "_core",
  "v1",
  "v2",
] }

[[bin]]
name = "uri_deserialize_pjuri"
path = "fuzz_targets/uri/deserialize_pjuri.rs"
doc = false
bench = false

[[bin]]
name = "url_decode_url"
path = "fuzz_targets/url/decode_url.rs"
doc = false
bench = false

[[bin]]
name = "directory_short_id"
path = "fuzz_targets/directory/short_id.rs"
doc = false
bench = false

[[bin]]
name = "url_arbitrary_url"
path = "fuzz_targets/url/arbitrary_url.rs"
doc = false
bench = false

[[bin]]
name = "uri_deserialize_pjuri_v2"
path = "fuzz_targets/uri/deserialize_pjuri_v2.rs"
doc = false
bench = false

[[bin]]
name = "roundtrip_v1"
path = "fuzz_targets/roundtrip/v1.rs"
doc = false
bench = false
