# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

import os
import sys
import ctypes
import enum
import struct
import contextlib
import datetime
import typing
import platform

# Used for default argument values
DEFAULT = object()


class RustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_int32),
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def alloc(size):
        return rust_call(_UniFFILib.ffi_pdk_ffi_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return rust_call(_UniFFILib.ffi_pdk_ffi_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return rust_call(_UniFFILib.ffi_pdk_ffi_rustbuffer_free, self)

    def __str__(self):
        return "RustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def allocWithBuilder(*args):
        """Context-manger to allocate a buffer using a RustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = RustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consumeWithStream(self):
        """Context-manager to consume a buffer using a RustBufferStream.

        The RustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = RustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError("junk data left in buffer at end of consumeWithStream")
        finally:
            self.free()

    @contextlib.contextmanager
    def readWithStream(self):
        """Context-manager to read a buffer using a RustBufferStream.

        This is like consumeWithStream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `RustBuffer` data.
        """
        s = RustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError("junk data left in buffer at end of readWithStream")

class ForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "ForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class RustBufferStream:
    """
    Helper for structured reading of bytes from a RustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def readI8(self):
        return self._unpack_from(1, ">b")

    def readU8(self):
        return self._unpack_from(1, ">B")

    def readI16(self):
        return self._unpack_from(2, ">h")

    def readU16(self):
        return self._unpack_from(2, ">H")

    def readI32(self):
        return self._unpack_from(4, ">i")

    def readU32(self):
        return self._unpack_from(4, ">I")

    def readI64(self):
        return self._unpack_from(8, ">q")

    def readU64(self):
        return self._unpack_from(8, ">Q")

    def readFloat(self):
        v = self._unpack_from(4, ">f")
        return v

    def readDouble(self):
        return self._unpack_from(8, ">d")

    def readCSizeT(self):
        return self._unpack_from(ctypes.sizeof(ctypes.c_size_t) , "@N")

class RustBufferBuilder:
    """
    Helper for structured writing of bytes into a RustBuffer.
    """

    def __init__(self):
        self.rbuf = RustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, numBytes):
        if self.rbuf.len + numBytes > self.rbuf.capacity:
            self.rbuf = RustBuffer.reserve(self.rbuf, numBytes)
        yield None
        self.rbuf.len += numBytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def writeI8(self, v):
        self._pack_into(1, ">b", v)

    def writeU8(self, v):
        self._pack_into(1, ">B", v)

    def writeI16(self, v):
        self._pack_into(2, ">h", v)

    def writeU16(self, v):
        self._pack_into(2, ">H", v)

    def writeI32(self, v):
        self._pack_into(4, ">i", v)

    def writeU32(self, v):
        self._pack_into(4, ">I", v)

    def writeI64(self, v):
        self._pack_into(8, ">q", v)

    def writeU64(self, v):
        self._pack_into(8, ">Q", v)

    def writeFloat(self, v):
        self._pack_into(4, ">f", v)

    def writeDouble(self, v):
        self._pack_into(8, ">d", v)

    def writeCSizeT(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class RustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", RustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_PANIC = 2

    def __str__(self):
        if self.code == RustCallStatus.CALL_SUCCESS:
            return "RustCallStatus(CALL_SUCCESS)"
        elif self.code == RustCallStatus.CALL_ERROR:
            return "RustCallStatus(CALL_ERROR)"
        elif self.code == RustCallStatus.CALL_PANIC:
            return "RustCallStatus(CALL_PANIC)"
        else:
            return "RustCallStatus(<invalid code>)"

def rust_call(fn, *args):
    # Call a rust function
    return rust_call_with_error(None, fn, *args)

def rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the FfiConverter for the error class that corresponds to the result.
    call_status = RustCallStatus(code=RustCallStatus.CALL_SUCCESS, error_buf=RustBuffer(0, 0, None))

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def rust_call_async(scaffolding_fn, callback_fn, *args):
    # Call the scaffolding function, passing it a callback handler for `AsyncTypes.py` and a pointer
    # to a python Future object.  The async function then awaits the Future.
    uniffi_eventloop = asyncio.get_running_loop()
    uniffi_py_future = uniffi_eventloop.create_future()
    uniffi_call_status = RustCallStatus(code=RustCallStatus.CALL_SUCCESS, error_buf=RustBuffer(0, 0, None))
    scaffolding_fn(*args,
       FfiConverterForeignExecutor._pointer_manager.new_pointer(uniffi_eventloop),
       callback_fn,
       # Note: It's tempting to skip the pointer manager and just use a `py_object` pointing to a
       # local variable like we do in Swift.  However, Python doesn't use cooperative cancellation
       # -- asyncio can cancel a task at anytime.  This means if we use a local variable, the Rust
       # callback could fire with a dangling pointer.
       UniFfiPyFuturePointerManager.new_pointer(uniffi_py_future),
       ctypes.byref(uniffi_call_status),
    )
    uniffi_check_call_status(None, uniffi_call_status)
    return uniffi_py_future

def uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == RustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == RustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == RustCallStatus.CALL_PANIC:
        # When the rust code sees a panic, it tries to construct a RustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = FfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid RustCallStatus code: {}".format(
            call_status.code))

# A function pointer for a callback as defined by UniFFI.
# Rust definition `fn(handle: u64, method: u32, args: RustBuffer, buf_ptr: *mut RustBuffer) -> int`
FOREIGN_CALLBACK_T = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_ulonglong, ctypes.c_ulong, ctypes.POINTER(ctypes.c_char), ctypes.c_int, ctypes.POINTER(RustBuffer))
class UniFfiPointerManagerCPython:
    """
    Manage giving out pointers to Python objects on CPython

    This class is used to generate opaque pointers that reference Python objects to pass to Rust.
    It assumes a CPython platform.  See UniFfiPointerManagerGeneral for the alternative.
    """

    def new_pointer(self, obj):
        """
        Get a pointer for an object as a ctypes.c_size_t instance

        Each call to new_pointer() must be balanced with exactly one call to release_pointer()

        This returns a ctypes.c_size_t.  This is always the same size as a pointer and can be
        interchanged with pointers for FFI function arguments and return values.
        """
        # IncRef the object since we're going to pass a pointer to Rust
        ctypes.pythonapi.Py_IncRef(ctypes.py_object(obj))
        # id() is the object address on CPython
        # (https://docs.python.org/3/library/functions.html#id)
        return id(obj)

    def release_pointer(self, address):
        py_obj = ctypes.cast(address, ctypes.py_object)
        obj = py_obj.value
        ctypes.pythonapi.Py_DecRef(py_obj)
        return obj

    def lookup(self, address):
        return ctypes.cast(address, ctypes.py_object).value

class UniFfiPointerManagerGeneral:
    """
    Manage giving out pointers to Python objects on non-CPython platforms

    This has the same API as UniFfiPointerManagerCPython, but doesn't assume we're running on
    CPython and is slightly slower.

    Instead of using real pointers, it maps integer values to objects and returns the keys as
    c_size_t values.
    """

    def __init__(self):
        self._map = {}
        self._lock = threading.Lock()
        self._current_handle = 0

    def new_pointer(self, obj):
        with self._lock:
            handle = self._current_handle
            self._current_handle += 1
            self._map[handle] = obj
        return handle

    def release_pointer(self, handle):
        with self._lock:
            return self._map.pop(handle)

    def lookup(self, handle):
        with self._lock:
            return self._map[handle]

# Pick an pointer manager implementation based on the platform
if platform.python_implementation() == 'CPython':
    UniFfiPointerManager = UniFfiPointerManagerCPython  # type: ignore
else:
    UniFfiPointerManager = UniFfiPointerManagerGeneral  # type: ignore
# Types conforming to `FfiConverterPrimitive` pass themselves directly over the FFI.
class FfiConverterPrimitive:
    @classmethod
    def check(cls, value):
        return value

    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return cls.lowerUnchecked(cls.check(value))

    @classmethod
    def lowerUnchecked(cls, value):
        return value

    @classmethod
    def write(cls, value, buf):
        cls.writeUnchecked(cls.check(value), buf)

class FfiConverterPrimitiveInt(FfiConverterPrimitive):
    @classmethod
    def check(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))
        return super().check(value)

class FfiConverterPrimitiveFloat(FfiConverterPrimitive):
    @classmethod
    def check(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))
        return super().check(value)

# Helper class for wrapper types that will always go through a RustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class FfiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consumeWithStream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with RustBuffer.allocWithBuilder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code,
# and the FFI Function declarations in a com.sun.jna.Library.
# Define some ctypes FFI types that we use in the library

"""
ctypes type for the foreign executor callback.  This is a built-in interface for scheduling
tasks

Args:
  executor: opaque c_size_t value representing the eventloop
  delay: delay in ms
  task: function pointer to the task callback
  task_data: void pointer to the task callback data

Normally we should call task(task_data) after the detail.
However, when task is NULL this indicates that Rust has dropped the ForeignExecutor and we should
decrease the EventLoop refcount.
"""
UNIFFI_FOREIGN_EXECUTOR_CALLBACK_T = ctypes.CFUNCTYPE(None, ctypes.c_size_t, ctypes.c_uint32, ctypes.c_void_p, ctypes.c_void_p)

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p)

def uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_size_t, return_type, RustCallStatus)

from pathlib import Path

def loadIndirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("pdk_ffi")
    path = str(Path(__file__).parent / libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 22
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_pdk_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def uniffi_check_api_checksums(lib):
    if lib.uniffi_pdk_ffi_checksum_method_scriptbuf_to_bytes() != 45806:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_method_scriptbuf_to_hex_string() != 60766:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_method_scriptbuf_to_string() != 60369:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_method_address_to_string() != 12154:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_method_uri_amount() != 48142:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_method_uri_address() != 9799:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_method_uri_check_pj_supported() != 6396:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_method_partiallysignedtransaction_serialize() != 44606:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_constructor_scriptbuf_new() != 58311:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_constructor_address_new() != 39137:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_constructor_headers_from_vec() != 39437:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_constructor_url_new() != 42932:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_constructor_uri_new() != 51867:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pdk_ffi_checksum_constructor_partiallysignedtransaction_new() != 53525:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniFFILib = loadIndirect()
_UniFFILib.uniffi_pdk_ffi_fn_free_scriptbuf.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_free_scriptbuf.restype = None
_UniFFILib.uniffi_pdk_ffi_fn_constructor_scriptbuf_new.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_constructor_scriptbuf_new.restype = ctypes.c_void_p
_UniFFILib.uniffi_pdk_ffi_fn_method_scriptbuf_to_bytes.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_method_scriptbuf_to_bytes.restype = RustBuffer
_UniFFILib.uniffi_pdk_ffi_fn_method_scriptbuf_to_hex_string.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_method_scriptbuf_to_hex_string.restype = RustBuffer
_UniFFILib.uniffi_pdk_ffi_fn_method_scriptbuf_to_string.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_method_scriptbuf_to_string.restype = RustBuffer
_UniFFILib.uniffi_pdk_ffi_fn_free_address.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_free_address.restype = None
_UniFFILib.uniffi_pdk_ffi_fn_constructor_address_new.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_constructor_address_new.restype = ctypes.c_void_p
_UniFFILib.uniffi_pdk_ffi_fn_method_address_to_string.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_method_address_to_string.restype = RustBuffer
_UniFFILib.uniffi_pdk_ffi_fn_free_headers.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_free_headers.restype = None
_UniFFILib.uniffi_pdk_ffi_fn_constructor_headers_from_vec.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_constructor_headers_from_vec.restype = ctypes.c_void_p
_UniFFILib.uniffi_pdk_ffi_fn_free_url.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_free_url.restype = None
_UniFFILib.uniffi_pdk_ffi_fn_constructor_url_new.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_constructor_url_new.restype = ctypes.c_void_p
_UniFFILib.uniffi_pdk_ffi_fn_free_uri.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_free_uri.restype = None
_UniFFILib.uniffi_pdk_ffi_fn_constructor_uri_new.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_constructor_uri_new.restype = ctypes.c_void_p
_UniFFILib.uniffi_pdk_ffi_fn_method_uri_amount.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_method_uri_amount.restype = RustBuffer
_UniFFILib.uniffi_pdk_ffi_fn_method_uri_address.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_method_uri_address.restype = ctypes.c_void_p
_UniFFILib.uniffi_pdk_ffi_fn_method_uri_check_pj_supported.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_method_uri_check_pj_supported.restype = ctypes.c_void_p
_UniFFILib.uniffi_pdk_ffi_fn_free_partiallysignedtransaction.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_free_partiallysignedtransaction.restype = None
_UniFFILib.uniffi_pdk_ffi_fn_constructor_partiallysignedtransaction_new.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_constructor_partiallysignedtransaction_new.restype = ctypes.c_void_p
_UniFFILib.uniffi_pdk_ffi_fn_method_partiallysignedtransaction_serialize.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_method_partiallysignedtransaction_serialize.restype = RustBuffer
_UniFFILib.uniffi_pdk_ffi_fn_free_prjuri.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.uniffi_pdk_ffi_fn_free_prjuri.restype = None
_UniFFILib.ffi_pdk_ffi_rustbuffer_alloc.argtypes = (
    ctypes.c_int32,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.ffi_pdk_ffi_rustbuffer_alloc.restype = RustBuffer
_UniFFILib.ffi_pdk_ffi_rustbuffer_from_bytes.argtypes = (
    ForeignBytes,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.ffi_pdk_ffi_rustbuffer_from_bytes.restype = RustBuffer
_UniFFILib.ffi_pdk_ffi_rustbuffer_free.argtypes = (
    RustBuffer,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.ffi_pdk_ffi_rustbuffer_free.restype = None
_UniFFILib.ffi_pdk_ffi_rustbuffer_reserve.argtypes = (
    RustBuffer,
    ctypes.c_int32,
    ctypes.POINTER(RustCallStatus),
)
_UniFFILib.ffi_pdk_ffi_rustbuffer_reserve.restype = RustBuffer
_UniFFILib.uniffi_pdk_ffi_checksum_method_scriptbuf_to_bytes.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_method_scriptbuf_to_bytes.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_method_scriptbuf_to_hex_string.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_method_scriptbuf_to_hex_string.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_method_scriptbuf_to_string.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_method_scriptbuf_to_string.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_method_address_to_string.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_method_address_to_string.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_method_uri_amount.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_method_uri_amount.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_method_uri_address.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_method_uri_address.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_method_uri_check_pj_supported.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_method_uri_check_pj_supported.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_method_partiallysignedtransaction_serialize.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_method_partiallysignedtransaction_serialize.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_scriptbuf_new.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_scriptbuf_new.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_address_new.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_address_new.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_headers_from_vec.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_headers_from_vec.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_url_new.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_url_new.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_uri_new.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_uri_new.restype = ctypes.c_uint16
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_partiallysignedtransaction_new.argtypes = (
)
_UniFFILib.uniffi_pdk_ffi_checksum_constructor_partiallysignedtransaction_new.restype = ctypes.c_uint16
_UniFFILib.ffi_pdk_ffi_uniffi_contract_version.argtypes = (
)
_UniFFILib.ffi_pdk_ffi_uniffi_contract_version.restype = ctypes.c_uint32
uniffi_check_contract_api_version(_UniFFILib)
uniffi_check_api_checksums(_UniFFILib)

# Public interface members begin here.


class FfiConverterUInt8(FfiConverterPrimitiveInt):
    CLASS_NAME = "u8"
    VALUE_MIN = 0
    VALUE_MAX = 2**8

    @staticmethod
    def read(buf):
        return buf.readU8()

    @staticmethod
    def writeUnchecked(value, buf):
        buf.writeU8(value)

class FfiConverterUInt32(FfiConverterPrimitiveInt):
    CLASS_NAME = "u32"
    VALUE_MIN = 0
    VALUE_MAX = 2**32

    @staticmethod
    def read(buf):
        return buf.readU32()

    @staticmethod
    def writeUnchecked(value, buf):
        buf.writeU32(value)

class FfiConverterUInt64(FfiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.readU64()

    @staticmethod
    def writeUnchecked(value, buf):
        buf.writeU64(value)

class FfiConverterString:
    @staticmethod
    def check(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.readI32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8Bytes = buf.read(size)
        return utf8Bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        value = FfiConverterString.check(value)
        utf8Bytes = value.encode("utf-8")
        buf.writeI32(len(utf8Bytes))
        buf.write(utf8Bytes)

    @staticmethod
    def lift(buf):
        with buf.consumeWithStream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        value = FfiConverterString.check(value)
        with RustBuffer.allocWithBuilder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()



class Address:
    _pointer: ctypes.c_void_p
    def __init__(self, address: "str"):
        
        self._pointer = rust_call_with_error(FfiConverterTypeError,_UniFFILib.uniffi_pdk_ffi_fn_constructor_address_new,
        FfiConverterString.lower(address))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_free_address, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def to_string(self, ) -> "str":
        return FfiConverterString.lift(
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_method_address_to_string,self._pointer,)
        )






class FfiConverterTypeAddress:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, Address):
            raise TypeError("Expected Address instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return Address._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class Headers:
    _pointer: ctypes.c_void_p

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_free_headers, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst

    @classmethod
    def from_vec(cls, body: "typing.List[int]"):
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = rust_call(_UniFFILib.uniffi_pdk_ffi_fn_constructor_headers_from_vec,
        FfiConverterSequenceUInt8.lower(body))
        return cls._make_instance_(pointer)



class FfiConverterTypeHeaders:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, Headers):
            raise TypeError("Expected Headers instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return Headers._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class PartiallySignedTransaction:
    _pointer: ctypes.c_void_p
    def __init__(self, psbt_base64: "str"):
        
        self._pointer = rust_call_with_error(FfiConverterTypeError,_UniFFILib.uniffi_pdk_ffi_fn_constructor_partiallysignedtransaction_new,
        FfiConverterString.lower(psbt_base64))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_free_partiallysignedtransaction, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def serialize(self, ) -> "typing.List[int]":
        return FfiConverterSequenceUInt8.lift(
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_method_partiallysignedtransaction_serialize,self._pointer,)
        )






class FfiConverterTypePartiallySignedTransaction:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, PartiallySignedTransaction):
            raise TypeError("Expected PartiallySignedTransaction instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return PartiallySignedTransaction._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class PrjUri:
    _pointer: ctypes.c_void_p

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_free_prjuri, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


class FfiConverterTypePrjUri:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, PrjUri):
            raise TypeError("Expected PrjUri instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return PrjUri._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class ScriptBuf:
    _pointer: ctypes.c_void_p
    def __init__(self, raw_output_script: "typing.List[int]"):
        
        self._pointer = rust_call(_UniFFILib.uniffi_pdk_ffi_fn_constructor_scriptbuf_new,
        FfiConverterSequenceUInt8.lower(raw_output_script))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_free_scriptbuf, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def to_bytes(self, ) -> "typing.List[int]":
        return FfiConverterSequenceUInt8.lift(
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_method_scriptbuf_to_bytes,self._pointer,)
        )






    def to_hex_string(self, ) -> "str":
        return FfiConverterString.lift(
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_method_scriptbuf_to_hex_string,self._pointer,)
        )






    def to_string(self, ) -> "str":
        return FfiConverterString.lift(
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_method_scriptbuf_to_string,self._pointer,)
        )






class FfiConverterTypeScriptBuf:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, ScriptBuf):
            raise TypeError("Expected ScriptBuf instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return ScriptBuf._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class Uri:
    _pointer: ctypes.c_void_p
    def __init__(self, uri: "str"):
        
        self._pointer = rust_call_with_error(FfiConverterTypeError,_UniFFILib.uniffi_pdk_ffi_fn_constructor_uri_new,
        FfiConverterString.lower(uri))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_free_uri, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def amount(self, ) -> "typing.Optional[int]":
        return FfiConverterOptionalUInt64.lift(
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_method_uri_amount,self._pointer,)
        )






    def address(self, ) -> "Address":
        return FfiConverterTypeAddress.lift(
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_method_uri_address,self._pointer,)
        )






    def check_pj_supported(self, ) -> "PrjUri":
        return FfiConverterTypePrjUri.lift(
            rust_call_with_error(
    FfiConverterTypeError,_UniFFILib.uniffi_pdk_ffi_fn_method_uri_check_pj_supported,self._pointer,)
        )






class FfiConverterTypeUri:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, Uri):
            raise TypeError("Expected Uri instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return Uri._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer



class Url:
    _pointer: ctypes.c_void_p
    def __init__(self, input: "str"):
        
        self._pointer = rust_call_with_error(FfiConverterTypeError,_UniFFILib.uniffi_pdk_ffi_fn_constructor_url_new,
        FfiConverterString.lower(input))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            rust_call(_UniFFILib.uniffi_pdk_ffi_fn_free_url, pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


class FfiConverterTypeUrl:
    @classmethod
    def read(cls, buf):
        ptr = buf.readU64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value, buf):
        if not isinstance(value, Url):
            raise TypeError("Expected Url instance, {} found".format(value.__class__.__name__))
        buf.writeU64(cls.lower(value))

    @staticmethod
    def lift(value):
        return Url._make_instance_(value)

    @staticmethod
    def lower(value):
        return value._pointer


class OutPoint:

    def __init__(self, txid, vout):
        self.txid = txid
        self.vout = vout

    def __str__(self):
        return "OutPoint(txid={}, vout={})".format(self.txid, self.vout)

    def __eq__(self, other):
        if self.txid != other.txid:
            return False
        if self.vout != other.vout:
            return False
        return True

class FfiConverterTypeOutPoint(FfiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return OutPoint(
            txid=FfiConverterString.read(buf),
            vout=FfiConverterUInt32.read(buf),
        )

    @staticmethod
    def write(value, buf):
        FfiConverterString.write(value.txid, buf)
        FfiConverterUInt32.write(value.vout, buf)


# Error
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class Error(Exception):
    pass

UniFFITempError = Error

class Error:  # type: ignore
    class InvalidAddress(UniFFITempError):
        def __repr__(self):
            return "Error.InvalidAddress({})".format(repr(str(self)))
    UniFFITempError.InvalidAddress = InvalidAddress  # type: ignore
    class InvalidScript(UniFFITempError):
        def __repr__(self):
            return "Error.InvalidScript({})".format(repr(str(self)))
    UniFFITempError.InvalidScript = InvalidScript  # type: ignore
    class PsbtParseError(UniFFITempError):
        def __repr__(self):
            return "Error.PsbtParseError({})".format(repr(str(self)))
    UniFFITempError.PsbtParseError = PsbtParseError  # type: ignore
    class ReceiveError(UniFFITempError):
        def __repr__(self):
            return "Error.ReceiveError({})".format(repr(str(self)))
    UniFFITempError.ReceiveError = ReceiveError  # type: ignore
    class RequestError(UniFFITempError):
        def __repr__(self):
            return "Error.RequestError({})".format(repr(str(self)))
    UniFFITempError.RequestError = RequestError  # type: ignore
    class SelectionError(UniFFITempError):
        def __repr__(self):
            return "Error.SelectionError({})".format(repr(str(self)))
    UniFFITempError.SelectionError = SelectionError  # type: ignore
    class CreateRequestError(UniFFITempError):
        def __repr__(self):
            return "Error.CreateRequestError({})".format(repr(str(self)))
    UniFFITempError.CreateRequestError = CreateRequestError  # type: ignore
    class PjParseError(UniFFITempError):
        def __repr__(self):
            return "Error.PjParseError({})".format(repr(str(self)))
    UniFFITempError.PjParseError = PjParseError  # type: ignore
    class PjNotSupported(UniFFITempError):
        def __repr__(self):
            return "Error.PjNotSupported({})".format(repr(str(self)))
    UniFFITempError.PjNotSupported = PjNotSupported  # type: ignore
    class UnexpectedError(UniFFITempError):
        def __repr__(self):
            return "Error.UnexpectedError({})".format(repr(str(self)))
    UniFFITempError.UnexpectedError = UnexpectedError  # type: ignore

Error = UniFFITempError  # type: ignore
del UniFFITempError


class FfiConverterTypeError(FfiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.readI32()
        if variant == 1:
            return Error.InvalidAddress(
                FfiConverterString.read(buf),
            )
        if variant == 2:
            return Error.InvalidScript(
                FfiConverterString.read(buf),
            )
        if variant == 3:
            return Error.PsbtParseError(
                FfiConverterString.read(buf),
            )
        if variant == 4:
            return Error.ReceiveError(
                FfiConverterString.read(buf),
            )
        if variant == 5:
            return Error.RequestError(
                FfiConverterString.read(buf),
            )
        if variant == 6:
            return Error.SelectionError(
                FfiConverterString.read(buf),
            )
        if variant == 7:
            return Error.CreateRequestError(
                FfiConverterString.read(buf),
            )
        if variant == 8:
            return Error.PjParseError(
                FfiConverterString.read(buf),
            )
        if variant == 9:
            return Error.PjNotSupported(
                FfiConverterString.read(buf),
            )
        if variant == 10:
            return Error.UnexpectedError(
                FfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def write(value, buf):
        if isinstance(value, Error.InvalidAddress):
            buf.writeI32(1)
        if isinstance(value, Error.InvalidScript):
            buf.writeI32(2)
        if isinstance(value, Error.PsbtParseError):
            buf.writeI32(3)
        if isinstance(value, Error.ReceiveError):
            buf.writeI32(4)
        if isinstance(value, Error.RequestError):
            buf.writeI32(5)
        if isinstance(value, Error.SelectionError):
            buf.writeI32(6)
        if isinstance(value, Error.CreateRequestError):
            buf.writeI32(7)
        if isinstance(value, Error.PjParseError):
            buf.writeI32(8)
        if isinstance(value, Error.PjNotSupported):
            buf.writeI32(9)
        if isinstance(value, Error.UnexpectedError):
            buf.writeI32(10)





class Network(enum.Enum):
    BITCOIN = 1
    TESTNET = 2
    SIGNET = 3
    REGTEST = 4
    


class FfiConverterTypeNetwork(FfiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.readI32()
        if variant == 1:
            return Network.BITCOIN
        if variant == 2:
            return Network.TESTNET
        if variant == 3:
            return Network.SIGNET
        if variant == 4:
            return Network.REGTEST
        raise InternalError("Raw enum value doesn't match any cases")

    def write(value, buf):
        if value == Network.BITCOIN:
            buf.writeI32(1)
        if value == Network.TESTNET:
            buf.writeI32(2)
        if value == Network.SIGNET:
            buf.writeI32(3)
        if value == Network.REGTEST:
            buf.writeI32(4)




class FfiConverterOptionalUInt64(FfiConverterRustBuffer):
    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.writeU8(0)
            return

        buf.writeU8(1)
        FfiConverterUInt64.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.readU8()
        if flag == 0:
            return None
        elif flag == 1:
            return FfiConverterUInt64.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class FfiConverterSequenceUInt8(FfiConverterRustBuffer):
    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.writeI32(items)
        for item in value:
            FfiConverterUInt8.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.readI32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            FfiConverterUInt8.read(buf) for i in range(count)
        ]

__all__ = [
    "InternalError",
    "Error",
    "Network",
    "OutPoint",
    "ScriptBuf",
    "Address",
    "Headers",
    "Url",
    "Uri",
    "PartiallySignedTransaction",
    "PrjUri",
]

