name: Set up nix
description: >
  Install nix with cache.
  Must run after actions/checkout so the cache can key off the repository
  contents.
runs:
  using: composite
  steps:
    - name: Install nix
      uses: DeterminateSystems/determinate-nix-action@main
    - name: Use nix cache
      uses: nix-community/cache-nix-action@v7
      with:
        primary-key: nix-${{ runner.os }}-${{ github.job }}-${{ hashFiles('flake.nix', 'flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-${{ github.job }}-
        gc-max-store-size: 1G
        purge: true
        purge-prefixes: nix-${{ runner.os }}-${{ github.job }}-
        purge-created: 0
        purge-primary-key: never
