name: Build and Test Dart
on:
  workflow_run:
    workflows: ["Flake maintenance"]
    types: [requested]
    branches:
      - "update_flake_lock_action"
  pull_request:
    paths:
      - payjoin-ffi/**

jobs:
  build-dart-and-test:
    name: "Build and test dart"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: "Use cache"
        uses: Swatinem/rust-cache@v2
      - name: "Install nix"
        uses: DeterminateSystems/determinate-nix-action@main
      - name: "Use nix cache"
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: "Build and test"
        run: nix develop .#dart -c bash ./payjoin-ffi/dart/contrib/test.sh
