name: Formatting

on: [push, pull_request]

jobs:
  Format:
    runs-on: ubuntu-26.04
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6
      - name: Set up nix
        uses: ./.github/actions/setup-nix
      - name: Run treefmt
        run: |
          set -eo pipefail
          nix fmt -- --ci || {
            echo "❌ Code is not formatted. Showing diff:"
            git --no-pager diff
            exit 1
          }
