name: Cargo lock maintenance
on:
  schedule:
    - cron: "0 20 * * 0" # weekly at 20:00 UTC
  workflow_dispatch:

jobs:
  update-lock-files:
    runs-on: ubuntu-latest
    env:
      UPDATE_DEPS: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - run: bash contrib/update-lock-files.sh
      - uses: peter-evans/create-pull-request@v7
        with:
          title: "chore: update cargo.lock"
          commit-message: "chore: update cargo.lock"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          branch: chore/cargo-lock-update
          add-paths: |
            Cargo-minimal.lock
            Cargo-recent.lock
