name: "Build and publish Docker image"

on:
  pull_request:
    paths:
      - payjoin-mailroom/**
  push:
    tags:
      - payjoin-mailroom-[0-9]*
  workflow_dispatch:

jobs:
  publish:
    name: "Build and publish Docker image"
    if: github.event_name != 'pull_request'
    strategy:
      fail-fast: false
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false # unneeded: no git auth beyond checkout

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # main

      - name: Log in to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAYJOIN_DOCKER_RW }}

      - name: Build and release image
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        # --impure is needed to pass env variables into the flake.
        # This breaks deterministic builds but allows us to identify
        # the image with the release tag name.
        run: nix run --impure .#packages.x86_64-linux.payjoin-mailroom-image.copyToRegistry

  build-pr:
    name: "Build and upload image artifact"
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Wait for other workflows
        uses: lewagon/wait-on-check-action@a499964d3917700d29a2a8baf3f16b078d609410 # v1.5.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          running-workflow-name: "Build and upload image artifact"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false # unneeded: no git auth beyond checkout

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # main

      - name: Build and save image artifact
        run: |
          TAG=$(git rev-parse --short HEAD)

          nix build .#packages.x86_64-linux.payjoin-mailroom-image.copyToDockerDaemon
          result/bin/copy-to-docker-daemon

          docker save docker.io/payjoin/payjoin-mailroom:${TAG} -o payjoin-mailroom-${TAG}.tar

          echo "Image saved: payjoin-mailroom-${TAG}.tar"
          ls -lh payjoin-mailroom-${TAG}.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: payjoin-mailroom-image-${{ github.sha }}
          path: payjoin-mailroom-*.tar
          retention-days: 7
